### ISSUE TITLE
Turtle code under Chapter 8 (Fractals)

### ISSUE THREAD

**Issue by XyLoNaMiyX** [shiffman/The-Nature-of-Code#102]
When showing the [turtle](http://natureofcode.com/book/chapter-8-fractals/) code, there's a part that says:

> Assuming we have a sentence generated from the L-system, we can walk through the sentence character by character and call the appropriate function as outlined above.

```java
  ...

  char c = sentence.charAt(i);

  if (c == 'F') {
    line(0,0,len,0);
    translate(len,0);
  } else if (c == 'F') {
   translate(len,0);
  } else if (c == '+') {

  ...
```

The second 'F' should be a 'G', the book is AMAZING though!

**Comment by shiffman** [comment]
Thanks, this has been fixed for the next edition!
