### ISSUE TITLE
6.7 The Dot Product, small math typo.

### ISSUE THREAD

**Issue by alelyya** [shiffman/The-Nature-of-Code#113]
On http://natureofcode.com/book/chapter-6-autonomous-agents/ chapter 6.7
Dot product of A(-3,5) and B(10,1):
-30+5=-25, not 35.

**Comment by alelyya** [comment]
btw, i found that typo at
http://natureofcode.com/book/chapter-6-autonomous-agents/

**Comment by drguildo** [comment]
This seems to have been fixed in 80340f918ce3ab34669eab30e0bcf95d77a1c17e.

**Comment by alelyya** [comment]
Yes, online version of the book seems to be a bit out of date.

**Comment by shiffman** [comment]
Yes, apologies too many things to do, I'll be returning to this project in early 2017.
