### ISSUE TITLE
Build problem with magicbook

### ISSUE THREAD

**Issue by kkshmz** [shiffman/The-Nature-of-Code#137]
Running macOS Sierra

Hi, wanting to clear out some of the issues that are here, which at most seem pretty basic ones, but I am unable to build with the magicbook.
Getting a error here, wondering if anyone else got this as well.
```
Error: Prince#execute: cannot resolve binary "prince" to a filesystem path

```

**Comment by shiffman** [comment]
I haven't looked at this project in a while (but do hope to get back to it soon!). You probably need to install princexml. . more instructions here:

http://www.princexml.com/download/

More:
https://github.com/runemadsen/Magic-Book-Project#installing-the-app

**Comment by kkshmz** [comment]
Thanks, was able to build, will contribute in squashing some of the issues!
