### ISSUE TITLE
atan using x/y instead of y/x

### ISSUE THREAD

**Issue by asalga** [shiffman/The-Nature-of-Code#14]
In chapter 3, oscillation, why is atan being passed in x/y, shouldn't it be y/x?

<p><span class="formula">V1 &rArr; angle = atan(-4/3) = atan(-1.25) = -0.9272952 radians = -53 degrees</span><br />
<span class="formula">V2 &rArr; angle = atan(4/-3) = atan(-1.25) = -0.9272952 radians = -53 degrees</span></p>

**Comment by shiffman** [comment]
This is now how it looks, I believe this is right.  Let me know if not:

<img width="680" alt="screen shot 2016-06-23 at 11 27 26 am" src="https://cloud.githubusercontent.com/assets/191758/16309122/9d5fe044-3935-11e6-8273-3d840a8acc41.png">
