### ISSUE TITLE
Missing <p> Tag

### ISSUE THREAD

**Issue by nonas-hunter** [shiffman/The-Nature-of-Code#152]
https://github.com/shiffman/The-Nature-of-Code/blob/d1d33748e07e0bc74dbf1b617c2c271a60c96a2e/chapters/00_7_intro.html#L673

Should there be a `<p>` tag around this line of text?
Right now it appears smaller than the surrounding text -- was that intentional?

**Comment by shiffman** [comment]
Yes, I believe this is just an error where the `<p>` tag was left out by accident!

**Comment by nonas-hunter** [comment]
Closing issue since it has been fixed with pull request #155
