### ISSUE TITLE
Possible typo in Ch1: Distributive rule for vectors

### ISSUE THREAD

**Issue by edwardball** [shiffman/The-Nature-of-Code#18]
Hello! Love this book.

Just wanted to query what you've written in Chapter 1 for the distributive rule:

`The distributive rule with 2 scalars, 1 vector: (n*m)*v⃗ =n*v⃗ + m*v⃗ `

Did you mean this instead?

`The distributive rule with 2 scalars, 1 vector: (n+m)*v⃗ =n*v⃗ + m*v⃗ `

**Comment by shiffman** [comment]
Should be correct now.

Old:

<img width="591" alt="screen shot 2016-06-23 at 1 58 04 pm" src="https://cloud.githubusercontent.com/assets/191758/16314179/aea57282-394a-11e6-890f-216f14b80b3c.png">

New (ignore math formula formatting still working on that):

<img width="642" alt="screen shot 2016-06-23 at 1 58 08 pm" src="https://cloud.githubusercontent.com/assets/191758/16314186/b632d3d2-394a-11e6-94eb-41b9697342d3.png">
