### ISSUE TITLE
typo in introduction

### ISSUE THREAD

**Issue by mnopqr** [shiffman/The-Nature-of-Code#20]
In the code after the text "Taking this further, we could use floating point numbers (i.e. decimal numbers) for x and y instead and move according to an arbitrary random value between -1 and 1." the command 

```
float stepx = random(-1, 1);
```

should be replaced by 
```
float stepx = random(-1, 2);
```
Similarly for ```stepy```.

**Comment by MarkSkilbeck** [comment]
Just writing to say this still hasn't been fixed, and left me puzzled for a few minutes.

**Comment by shiffman** [comment]
Ok, here is the revised text.  How does this sound?

><p>Taking this further, we could use floating point numbers (i.e. decimal numbers)  move according to an arbitrary random value between -1 and 1.</p>
>
><pre data-code-language="java" data-type="programlisting" class="codesplit">
class Walker {
  // x and y are now floats
  float x;
  float y;
</pre>
>
><p>Now that <code>x</code> and <code>y</code> are floats, the output of the <code>random()</code> function can be directly applied.</p>
>
><pre data-code-language="java" data-type="programlisting" class="codesplit">
  void step() {
    //{!2} Yields any floating point number between -1.0 and 1.0
    float xstep = random(-1, 1);
    float ystep = random(-1, 1);
    x += xstep;
    y += ystep;
  }</pre>
