### ISSUE TITLE
Typo on page 34

### ISSUE THREAD

**Issue by NomadLeirbag** [shiffman/The-Nature-of-Code#22]
In the print book, at the bottom of page 34 (chapter 1: Vectors), it reads

Then, replacing u and v with their values from Figure 1.6, we get:
wx = 5 + 3
which means that:
Finally, we write that as a vector:
w = (8, 6)

On the online version, this section reads

Then, replacing u and v with their values from Figure 1.6, we get:
wx = 5 + 3
wy = 2 + 4
which means that:
wx = 8 wy = 6
Finally, we write that as a vector:
w = (8, 6)

**Comment by shiffman** [comment]
This error occurred due to faulty math formula rendering, I'm going to leave this open just so I double check but once the new math rendering is in this should be fixed.

**Comment by shiffman** [comment]
yay, this is working now!

<img width="745" alt="screen shot 2016-07-11 at 11 42 59 am" src="https://cloud.githubusercontent.com/assets/191758/16736818/a4b4b89e-475c-11e6-9ff3-b70ae64c7600.png">
