### ISSUE TITLE
Vector Propertie Mistake

### ISSUE THREAD

**Issue by Jordan2R** [shiffman/The-Nature-of-Code#29]
First of all, thanks for doing this book. I'm in love with it, it's totally awesome, great job!

I think there is a mistake on:

http://natureofcode.com/book/chapter-1-vectors/

at "More Number Properties with Vectors". More specifically at "The distributive rule with 2 scalars, 1 vector: (n*m)*v". Shouldn't it be:

The distributive rule with 2 scalars, 1 vector: (n+m)*v ??? Or am I wrong? If I am, sorry about this ^^

**Comment by shiffman** [comment]
Yes, that's right.  #18
