### ISSUE TITLE
Friction

### ISSUE THREAD

**Issue by Jordan2R** [shiffman/The-Nature-of-Code#31]
First of all, I don't want to be considered as a spammer or something. I'm just trying to help. I wonder if you prefer me to create a Github Issue for each little mistake I find or you prefer me reading a lot of the book before creating one? I personally think creating one for each would be the best, since each error would be represented by an Issue. But if you don't prefer like that, I can do the other way around.

Well, what I want to talk about friction is that the way you did, it's happening all the time (you said something like that yourself). But shouldn't it happen only when the object is on a surface? That is easily checkable with an if. I'm sorry doing these questions/issues, it's just I'm really enjoying this book and I want to understand everything well and correct.

**Comment by shiffman** [comment]
This is obviously an incredibly late reply but I am only now returning to work on this book for a 2nd edition.  A separate issue for each correction is best yes!

Yes, it's a little weird that I am applying friction all the time. . like the window in a surface the object is sliding on.  This is not really like actual friction in a 3D world.  I believe this is clear from my discussion in the book, but if there's a particular paragraph that is misleading or unclear, let me know!
