### ISSUE TITLE
Typing errors

### ISSUE THREAD

**Issue by gmqi** [shiffman/The-Nature-of-Code#34]
Chapter 1. Vectors
Vector multiplication
More Number Properties with Vectors

I think the following sentence
The distributive rule with 2 scalars, 1 vector: (n*m)*v⃗ =n*v⃗ +m*v⃗
should be
The distributive rule with 2 scalars, 1 vector: (n+m)*v⃗ =n*v⃗ +m*v⃗

How do you think?

**Comment by shiffman** [comment]
Fixed, see: #18
