### ISSUE TITLE
Misleading definition of the Normal distribution

### ISSUE THREAD

**Issue by trueNico** [shiffman/The-Nature-of-Code#41]
At the beginning of "I.4 A Normal Distribution of Random Numbers", it is said:

>A distribution of values that cluster around an average (referred to as the “mean”) is known as a “normal” distribution.

This is very misleading, because a distribution of values that cluster around an average is not necessarily a normal distribution. There are maaaany other distributions that are also clustered around the mean (exples: the Cauchy distribution, the Laplace distribution, the t-distribution...)
A normal distribution is one of these, yes, but a very special case and the "clustered around the mean" is by no means its definition.

**Comment by shiffman** [comment]
Ah, thank you, yes, this is a big problem I'm very glad for the report.  Hope to get to making revisions later this summer.

**Comment by shiffman** [comment]
https://github.com/shiffman/The-Nature-of-Code/commit/714643420a30ee2bc52a0e2213fa4c8b8ac2d45f changes the text to read as follows:

> One example of a distribution of values that cluster around an average (referred to as the “mean”) is called a “normal” distribution. It is also sometimes referred to as the Gaussian distribution (named for mathematician Carl Friedrich Gauss).
>
> When you graph this distribution, you get something that looks like the following, informally known as a bell curve:

How does this sound to you?  I'm closing for now but will re-open if it's still a problem.  Open to suggestions!

**Comment by trueNico** [comment]
Yes, it's not misleading anymore!

I think it could be nice to also acknowledge that this is not a random
example though, by saying
"*A famous* example of a distribution of values that...", or "*An important*
example of a distribution of values that...".
instead of
"*One *example of a distribution of values"
Cheers,

Nicolas

**Comment by shiffman** [comment]
Awesome, going with "one of the most famous examples. . . "

**Comment by trueNico** [comment]
👍
