### ISSUE TITLE
Incorrect URL to Magic Book Project

### ISSUE THREAD

**Issue by mjangda** [shiffman/The-Nature-of-Code#43]
In the Preface P4, the link to the Magic Book Project is incorrect.

http://www.magicbookproject.com leads to a domain parked page.

The correct URL seems to be https://github.com/runemadsen/Magic-Book-Project

**Comment by shiffman** [comment]
Thanks, the book is now being built via https://atlas.oreilly.com/ and once I got that working I'll be able to make updates!  I'll mention magic book (corrected url: https://github.com/runemadsen/Magic-Book-Project) still for history.

**Comment by shiffman** [comment]
And now we're back to magic book again!  updated the link, but going to open a new issue that the Preface has to be rewritten to update new technologies.
