### ISSUE TITLE
(Potentially) Incorrect references to graph locations in I.4

### ISSUE THREAD

**Issue by mjangda** [shiffman/The-Nature-of-Code#44]
> The graphs above should give us a hint. The graph on the left shows us the distribution with a very low standard deviation, where the majority of the values cluster closely around the mean. The graph on the right shows us a higher standard deviation, where the values are more evenly spread out from the average.

I'm viewing the ePub in Google Play Books which stacks the two graphs on top of each other:

![nature-of-code-play-books-i4](https://cloud.githubusercontent.com/assets/86105/8097631/db6280d4-0fb2-11e5-8676-193d5d722839.png)

That makes it hard to figure out which one the text is referencing which it says "on the left" or "on the right". Referencing them using their `Figure` number would be better.

**Comment by shiffman** [comment]
ah, thanks for the report!

**Comment by shiffman** [comment]
Fixed!
