### ISSUE TITLE
Intro-1.4: Using the Random class (Processing 3.0.1)

### ISSUE THREAD

**Issue by HazemAlhalabi** [shiffman/The-Nature-of-Code#53]
Online book, Introduction-1.4 mentions:
>Instead, we can make use of a class known as Random, which we get for free as part of the default Java libraries imported into Processing.
>To use the Random class, we must first declare a variable of type Random and create the Random object in setup().

```processing
Random generator;

void setup() {
  size(640,360);
  generator = new Random();
}
```
In Processing 3.0.1 this didn't work for me without importing `java.util.Random` to the sketch. 

I know this is not part of the examples but I'm posting the issue because I think it can be a source of confusion for beginner readers using the latest version of Processing.

*P.S. Thanks a lot for making the book. Can't wait for the next edition!*

**Comment by shiffman** [comment]
Yes, this changed with 3.0.  You can now actually use the new `randomGaussian()` function too!  I'll make sure this is updated in the next edition.

**Comment by HazemAlhalabi** [comment]
Awesome! Thanks a lot!

**Comment by shiffman** [comment]
Now covered in #12.
