### ISSUE TITLE
error in web book in section 1.4

### ISSUE THREAD

**Issue by anisnazer** [shiffman/The-Nature-of-Code#54]
I just want to thank you for providing this wonderful book for free and would like to note a small mistake in section 1.4 where you give an example on calculating mean and standard deviation. The value of the average variance should be 228.81 not 254.23 as mentioned. The value of the standard deviation is correct though. 

Thanks
Anis Nazer

**Comment by shiffman** [comment]
Thanks for pointing this out!

**Comment by shiffman** [comment]
I believe the following should be correct:

```
85, 82, 88, 86, 85, 93, 98, 40, 73, 83

mean: 81.3
average variance: 228.81
standard dev: 15.13
```

I was using "sample" variance / standard deviation but I believe "population" variance / standard deviation is best here.

https://statistics.laerd.com/statistical-guides/measures-of-spread-standard-deviation.php

Would be glad for feedback / confirmation.
