### ISSUE TITLE
Chap 1 - Vector Subtraction - where to call translate()

### ISSUE THREAD

**Issue by dlehrich** [shiffman/The-Nature-of-Code#57]
Working through the Nature of Code w/ p5js. I'm using the p5 editor version 0.5.7

In the vector subtraction example (https://github.com/shiffman/The-Nature-of-Code-Examples-p5.js/blob/master/chp01_vectors/NOC_1_03_vector_subtraction/sketch.js)... if I run this code as-is, I see a line blip from the top left corner to center on frame 1, then no other lines. However, if I move the translate() call into setup(), the sketch behaves as expected.

Is this a possible issue with the p5 editor? Or has p5js syntax been updated to change the way translate() works?

Thanks!

**Comment by shiffman** [comment]
This is this problem: https://github.com/processing/p5.js/issues/1174.  It has been fixed in newer version of p5.  You can get the newer p5.js library file or just put `push()` at start of `draw()` and `pop()` at end as a temporary fix.
