### ISSUE TITLE
4.3 The ArrayList: plist | particles

### ISSUE THREAD

**Issue by sejomagno** [shiffman/The-Nature-of-Code#59]
In the section where the "enhanced for loop" is first shown, the name of the ArrayList that is created is `plist`, but the name of the list that is inside the loop is `particles`. Apparently the name `plist` comes from the comparison between an array and a list (`parray` vs `plist`). However, as the name that is used throughout the chapter is `particles`, that specific example got a mix of both names.

**Comment by shiffman** [comment]
Thanks for pointing out the error!

**Comment by shiffman** [comment]
did you mean to close this?   Need to make sure it's fixed so will re-open.

**Comment by sejomagno** [comment]
Yes, I meant it! After watching your videos about Github I wanted to help
fixing this issue. However, I could see that here (not in the book site) it
is already corrected. I was not able to track which commit had the
correction. I wanted to explain this when I closed the issue but I didn't
find the space. Sorry and thanks!

**Comment by shiffman** [comment]
got it!
