### ISSUE TITLE
Broken link on 'further reading' page

### ISSUE THREAD

**Issue by rik-brown** [shiffman/The-Nature-of-Code#61]
A link on this page appears to be broken: http://natureofcode.com/book/further-reading/

The link in question is : http://www.processing.org/learning/books
in the sentence "For other books that use Processing, see Processing Books."

I think the correct link could be: https://processing.org/books/

**Comment by jschulenklopper** [comment]
Good catch. This is already corrected in the source code of the book, via commit https://github.com/shiffman/The-Nature-of-Code/commit/cfedebc75cffc87d6a8aa5bfa11a8a0032be304d, but only the HTML of the book needs to be regenerated and pushed online.

**Comment by shiffman** [comment]
Will leave open until the website is regenerated.

**Comment by shiffman** [comment]
no need to leave open, new website should arrive by end of summer (fingers crossed).
