### ISSUE TITLE
Problem in the values of the section I.4

### ISSUE THREAD

**Issue by palosastre** [shiffman/The-Nature-of-Code#70]
Hello! I'm Paloma Sastre from Chile, and I'm a big fan of yours. I'm at Universidad del Desarrollo studying Digital Design, and I had a class where our teacher teached us Processing, and I liked it a lot and used a lot of your videos on Youtube to understand it better. Now that I finished that class, I wanted to continue learning so I downloaded your book.
In the section I.4, in the part of "Calculating Mean and Standard Deviation", I had a problem because I calculated the Difference from Mean and the Variance of every student you named before, and the Average Variance I got, wasn't the one that is written in the book. I got 228.81.
So I wanted to ask you if I did something wrong, or maybe the version I downloaded wasn't actualized. I also looked for it in the web version of your book, and it also says that the Average Variance is 254.23.

Thank you! Looking forward for your answer.
Greetings from Chile.

**Comment by shiffman** [comment]
This was my mistake, fixed now see: #54
