### ISSUE TITLE
Chapter 8 if-else if - Java needs the final return (not Processing)

### ISSUE THREAD

**Issue by CreamyCookie** [shiffman/The-Nature-of-Code#75]
In chapter 8 there's a [statement](https://github.com/shiffman/The-Nature-of-Code/blob/82312c7faff0c9b566bf8028429b313489cf8a85/chapters/07_ca.html#L355) that says

>  For this function to be valid, we have to make sure something is returned in cases where the states do not match one of the eight possibilities. **We know this is impossible given the rest of our code, but Processing does not.**

But that's a "limit" of Java not Processing. The Java compiler makes sure that the function returns an `int` if the return type is `int`, but it doesn't know that the last return will never be reached (in this case).

**Comment by shiffman** [comment]
Thanks, I realize I'm being a bit informal with the use of Processing.  I've changed it to say Processing (Java).
