### ISSUE TITLE
Broken links in Chapter 7

### ISSUE THREAD

**Issue by CreamyCookie** [shiffman/The-Nature-of-Code#76]
Both of [these links](https://github.com/shiffman/The-Nature-of-Code/blob/82312c7faff0c9b566bf8028429b313489cf8a85/chapters/07_ca.html#L697) are broken:

https://llk.media.mit.edu/projects/emergence/

    Exploring Emergence by Mitchel Resnick and Brian Silverman, Lifelong Kindergarten Group, MIT Media Laboratory

http://stevenklise.github.com/ConwaysGameOfLife

    Conway’s Game of Life by Steven Klise (uses Processing.js!)

**Comment by shiffman** [comment]
@sklise looking at your repo it looks like maybe you started porting to p5.js?  Would you like me to keep a reference to this project in the book?  I would be glad to help with the port.  Is there a new URL?

**Comment by shiffman** [comment]
Here's the new exploring emergence link for when I get to it: http://www.playfulinvention.com/emergence/

**Comment by sklise** [comment]
@shiffman what a fortuitous day to have a five hour flight. Rewritten in p5.js and up at https://sklise.github.io/conways-game-of-life/

in 2016 I'm much less likely to change my username or push un-runnable code.

I hope to add more documentation, and interaction. But also open to PRs 😄

**Comment by shiffman** [comment]
Awesome, thank you!  I'd love to help add some interaction at some point.
