### ISSUE TITLE
Do a pass over style guides and CSS

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#78]
Print style guides are here: https://www.dropbox.com/sh/8nm4wc76h23a9fe/AABhxqO_YTc69ERNk0VfLoq8a?dl=0

Goal is to match current PDF render as close as possible.  Am posting a general issue now and once a first pass is completed we can go through and post individual issues for style fixes.

**Comment by shiffman** [comment]
@alterebro Is it helpful if I do a scan over the designs + PDF and note issues that need fixing or do you prefer to do a pass over everything first?

**Comment by alterebro** [comment]
I'll make a first pass over all the styles.

**Comment by alterebro** [comment]
I think it is now ready for a first review.
In order to make the TOC we'll need to find out how to add some metadata (Chapter number and section number) to the pages so every list item has got the data needed on the views.

**Comment by shiffman** [comment]
Thanks for this, it's looking great.  I will do a review and make small fixes myself and post new issues for items I need help with.  I probably won't get to this until Monday.

**Comment by shiffman** [comment]
I'm closing this as I think we can discuss things in individual issues now.
