### ISSUE TITLE
Deal with codesplit offset for long lines

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#81]
Some lines of code are too long to fit the comment to the right.  I currently have an `offset` class in `_codesplit.scss` but it's not elegant.  The original idea was to have two offsets: `offset-up` and `offset-down`.  They looked like this in the first edition:

<img width="595" alt="screen shot 2016-07-06 at 10 38 33 am" src="https://cloud.githubusercontent.com/assets/191758/16621887/debe7548-4365-11e6-9c25-ea661d3e319b.png">

<img width="565" alt="screen shot 2016-07-06 at 10 38 39 am" src="https://cloud.githubusercontent.com/assets/191758/16621894/e13d2148-4365-11e6-8b87-5062259a2292.png">

But I'm open to alternate designs / solutions.

**Comment by alterebro** [comment]
The `.offset` class now by default will be shown below the code line and there's now an extra class (`.offset-top`) which will put the comment above the code.
