### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#84]
I'm opening this issue to track discussion / implementation of font sizes.  @alterebro's first pass over the stylesheets matched all the sizes specified in @CalxDesign's original design specs.  However, as I created the first edition, sizes got modified to fit more stuff on the page.  

I've changed the sizes in this commit: https://github.com/shiffman/The-Nature-of-Code/commit/1427a3013bbd63f51940b324be339cad7772c04c but am open to suggestions as to what looks nicest.  In addition, I have a feeling my use of `%` for the code sizing is probably not optimal.  Do we need to add another variable like `$font-XS` @alterebro?

**Comment by alterebro** [comment]
Yes, I've included the XS size, I think it's better to have absolute sizes just in case the classes for some reason are nested so they don't become smaller and smaller.
