### ISSUE TITLE
bold code not very noticeable

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#85]
This should appear as follows:

background(255);
**position.add(velocity);**

But it's not so noticeable in the current render:

<img width="232" alt="screen shot 2016-07-11 at 10 38 18 am" src="https://cloud.githubusercontent.com/assets/191758/16734492/b7e23c74-4753-11e6-9329-8bed9ff0c833.png">

Maybe something to do with droid_sans_monoregular?  I am curious to try Source Code Pro.  @calxdesign do you have an opinion?

**Comment by calxdesign** [comment]
Source Code Pro looks like a reasonable replacement if Droid Sans is causing issues. Yeah, let's try it.

**Comment by alterebro** [comment]
Yes, it looks better now, Droid Sans Mono family only had 1 weight.
