### ISSUE TITLE
Screenshot images should have thin outline

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#87]
1st edition:

<img width="697" alt="screen shot 2016-07-11 at 10 43 27 am" src="https://cloud.githubusercontent.com/assets/191758/16734679/6294d690-4754-11e6-9676-5288e267ae0f.png">

2nd edition:

<img width="672" alt="screen shot 2016-07-11 at 10 43 41 am" src="https://cloud.githubusercontent.com/assets/191758/16734684/67719158-4754-11e6-8351-a28f9a68258c.png">

There also looks like there is some sort of gradient / dropshadow above the image that should probably be removed?

**Comment by alterebro** [comment]
That was a try based on a previous comment on the CSS code:

```scss
// Need a magic solution for border side borders to be partial, not extend all the way to top
```
( https://github.com/shiffman/The-Nature-of-Code/commit/0d8fcabc8a60e54091a16e47d573d82231965ad7#diff-a134daaa45c2acf81732f755c99288b5L308 )


There was also a note on the pdf file from the dropbox (noc_dw_02.pdf) on those screenshot to make them look with a slight dropping shadow. I've switched back to the previous hard border version ( 7b0ee4b ) as anyway the PDF render wasn't the same as in the browser.

I leave the issue open just in case we want to put there the drop shadows

**Comment by shiffman** [comment]
Ah, now I remember.  The drop shadows looked nice in the design, but the actual printer doesn't have the ability to render such fine gray details so they didn't look good in the physical book. Print quality may have improved from 3-4 years ago, but I think let's stick to no drop shadows for now.

**Comment by alterebro** [comment]
ok no problem, we can close this.
