### ISSUE TITLE
Equation alignment?

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#88]
Would it be better to left-align all the `<div data-type="equation">` elements?  Or just have an option like `<div data-type="equation" class="center">` / `<div data-type="equation" class="left">`?

<img width="366" alt="screen shot 2016-07-11 at 10 45 50 am" src="https://cloud.githubusercontent.com/assets/191758/16734798/cf140930-4754-11e6-9529-ef84d023e9dd.png">

**Comment by alterebro** [comment]
There's a new class for this ( `.equation-left` ) to be used in a wrapper div as I couldn't figure out how to 'inject' a class from the `data-type="equation" div` to the generated `.katex` code.

```html
<!-- example -->
<div class="equation-left">
<div data-type="equation">\vec{w} = (8,6)</div>
</div>
```
