### ISSUE TITLE
code comment header?

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#92]
This is a bit of a weird one, but in rare instances I have a code comment not associated with a line of code that acts as a header for some comments below.   I could simply rewrite the comments to not do this or else perhaps create a class / style (grey box only on right side?) for this.  Right now it looks odd:

The "header" is "Our algorithm for calculating acceleration:"

<img width="681" alt="screen shot 2016-07-11 at 11 02 25 am" src="https://cloud.githubusercontent.com/assets/191758/16735457/199f28de-4757-11e6-9d14-ff2ed4ef4267.png">

**Comment by alterebro** [comment]
In order to achieve this I've created an extra class named `.comment-header`

```processing
void update() {

	//{.comment-header} Our algorithm for calculating acceleration:

	//{!2} Find the vector pointing towards the mouse.
	PVector mouse = new PVector(mouseX, mouseY);
	PVector dir = PVector.sub(mouse, position);
```
